Source access configuration
terraform-aws-modules/terraform-aws-lambda pull request #190
Opened 2021-08-17 13:59 UTC by Infra-Red

## Description

Allow to configure `queues` and `source_access_configuration` properties in [lambda_event_source_mapping](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping) configuration.

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-mq.html

## Motivation and Context

Add missing parameters that are required to configure AmazonMQ event source type.

## Breaking Changes

None.

## How Has This Been Tested?

Tested locally by modifying the `examples/event-source-mapping` module to include Amazon MQ event source.

2021-08-19 10:38 UTC, antonbabenko requested changes
Looks good. Please update code in `examples/event-source-mapping` to show this feature for real.

2021-08-19 11:45 UTC, Infra-Red commented
Updated with an Amazon MQ event source mapping example.

2021-08-19 12:30 UTC, antonbabenko commented
The example looks good but I can't make it to work locally and I don't have a lot of time today to investigate it.

Could you try to run that one example yourself locally?

2021-08-19 15:25 UTC, Infra-Red commented
Hi @antonbabenko, please find the result of `terraform plan` and `terraform apply` below.

<details><summary>1. terraform plan</summary>
<p>

```sh
> terraform plan -out .plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # aws_dynamodb_table.this will be created
  + resource "aws_dynamodb_table" "this" {
      + arn              = (known after apply)
      + billing_mode     = "PAY_PER_REQUEST"
      + hash_key         = "UserId"
      + id               = (known after apply)
      + name             = (known after apply)
      + range_key        = "GameTitle"
      + stream_arn       = (known after apply)
      + stream_enabled   = true
      + stream_label     = (known after apply)
      + stream_view_type = "NEW_AND_OLD_IMAGES"
      + tags_all         = (known after apply)

      + attribute {
          + name = "GameTitle"
          + type = "S"
        }
      + attribute {
          + name = "UserId"
          + type = "S"
        }

      + point_in_time_recovery {
          + enabled = (known after apply)
        }

      + server_side_encryption {
          + enabled     = (known after apply)
          + kms_key_arn = (known after apply)
        }
    }

  # aws_kinesis_stream.this will be created
  + resource "aws_kinesis_stream" "this" {
      + arn                       = (known after apply)
      + encryption_type           = "NONE"
      + enforce_consumer_deletion = false
      + id                        = (known after apply)
      + name                      = (known after apply)
      + retention_period          = 24
      + shard_count               = 1
      + tags_all                  = (known after apply)
    }

  # aws_mq_broker.this will be created
  + resource "aws_mq_broker" "this" {
      + apply_immediately          = false
      + arn                        = (known after apply)
      + authentication_strategy    = (known after apply)
      + auto_minor_version_upgrade = false
      + broker_name                = (known after apply)
      + deployment_mode            = "SINGLE_INSTANCE"
      + engine_type                = "RabbitMQ"
      + engine_version             = "3.8.17"
      + host_instance_type         = "mq.t3.micro"
      + id                         = (known after apply)
      + instances                  = (known after apply)
      + publicly_accessible        = false
      + storage_type               = (known after apply)
      + subnet_ids                 = (known after apply)
      + tags_all                   = (known after apply)

      + configuration {
          + id       = (known after apply)
          + revision = (known after apply)
        }

      + maintenance_window_start_time {
          + day_of_week = (known after apply)
          + time_of_day = (known after apply)
          + time_zone   = (known after apply)
        }

      + user {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }

  # aws_secretsmanager_secret.this will be created
  + resource "aws_secretsmanager_secret" "this" {
      + arn                            = (known after apply)
      + force_overwrite_replica_secret = false
      + id                             = (known after apply)
      + name                           = (known after apply)
      + name_prefix                    = (known after apply)
      + policy                         = (known after apply)
      + recovery_window_in_days        = 30
      + rotation_enabled               = (known after apply)
      + rotation_lambda_arn            = (known after apply)
      + tags_all                       = (known after apply)

      + replica {
          + kms_key_id         = (known after apply)
          + last_accessed_date = (known after apply)
          + region             = (known after apply)
          + status             = (known after apply)
          + status_message     = (known after apply)
        }

      + rotation_rules {
          + automatically_after_days = (known after apply)
        }
    }

  # aws_secretsmanager_secret_version.this will be created
  + resource "aws_secretsmanager_secret_version" "this" {
      + arn            = (known after apply)
      + id             = (known after apply)
      + secret_id      = (known after apply)
      + secret_string  = (sensitive value)
      + version_id     = (known after apply)
      + version_stages = (known after apply)
    }

  # aws_sqs_queue.failure will be created
  + resource "aws_sqs_queue" "failure" {
      + arn                               = (known after apply)
      + content_based_deduplication       = false
      + deduplication_scope               = (known after apply)
      + delay_seconds                     = 0
      + fifo_queue                        = false
      + fifo_throughput_limit             = (known after apply)
      + id                                = (known after apply)
      + kms_data_key_reuse_period_seconds = (known after apply)
      + max_message_size                  = 262144
      + message_retention_seconds         = 345600
      + name                              = (known after apply)
      + name_prefix                       = (known after apply)
      + policy                            = (known after apply)
      + receive_wait_time_seconds         = 0
      + tags_all                          = (known after apply)
      + url                               = (known after apply)
      + visibility_timeout_seconds        = 30
    }

  # aws_sqs_queue.this will be created
  + resource "aws_sqs_queue" "this" {
      + arn                               = (known after apply)
      + content_based_deduplication       = false
      + deduplication_scope               = (known after apply)
      + delay_seconds                     = 0
      + fifo_queue                        = false
      + fifo_throughput_limit             = (known after apply)
      + id                                = (known after apply)
      + kms_data_key_reuse_period_seconds = (known after apply)
      + max_message_size                  = 262144
      + message_retention_seconds         = 345600
      + name                              = (known after apply)
      + name_prefix                       = (known after apply)
      + policy                            = (known after apply)
      + receive_wait_time_seconds         = 0
      + tags_all                          = (known after apply)
      + url                               = (known after apply)
      + visibility_timeout_seconds        = 30
    }

  # random_password.this will be created
  + resource "random_password" "this" {
      + id          = (known after apply)
      + length      = 40
      + lower       = true
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = true
      + result      = (sensitive value)
      + special     = false
      + upper       = true
    }

  # random_pet.this will be created
  + resource "random_pet" "this" {
      + id        = (known after apply)
      + length    = 2
      + separator = "-"
    }

  # module.lambda_function.data.aws_iam_policy_document.additional_inline[0] will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "additional_inline"  {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "mq:DescribeBroker",
            ]
          + effect    = "Allow"
          + resources = [
              + (known after apply),
            ]
          + sid       = "mqdescribebroker"
        }
      + statement {
          + actions   = [
              + "ec2:DescribeSecurityGroups",
              + "ec2:DescribeSub [...]

2021-08-30 08:08 UTC, Infra-Red commented
Hi @antonbabenko, please review when you get a chance. Thanks!

2021-08-30 08:34 UTC, antonbabenko commented on examples/event-source-mapping/main.tf
> +  engine_version     = "3.8.17"
> Error: BadRequestException: Broker engine version [3.8.17] is invalid for broker engine type [RABBITMQ]. Valid values: [3.8.11, 3.8.6].

I update the code to use 3.8.11

2021-08-30 09:51 UTC, merged

2021-08-30 09:51 UTC, antonbabenko commented
Thanks @Infra-Red !

[v2.12.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v2.12.0) has been just released.