feat: Add support for AWS Graviton2 powered functions
terraform-aws-modules/terraform-aws-lambda pull request #206
Opened 2021-09-30 16:15 UTC by Infra-Red

## Description

Allow to configure `architectures` property in [aws_lambda_function](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function) and `compatible_architectures` property in [aws_lambda_layer_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version) configuration.

## Motivation and Context

Add missing parameter that is required to support AWS Lambda Functions Powered by AWS Graviton2 Processor.

https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

## Breaking Changes

None.

## How Has This Been Tested?
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

Closes #207

2021-09-30 18:39 UTC, antonbabenko requested changes
Thank you for this PR! The draft looks great, there are couple of small things to do:
1. Update minimum version requirements in `versions.tf` everywhere and rerun `pre-commit run -a` to fix documentation (when the updated provider is released)?
2. Add support for the same feature in the Lambda Layer resource (`compatible_architectures`)?
3. Update example code to have at least one function deploying using `arm64` architecture.

If you can, please double-check whether we need to do anything in `package.{tf,py}` related to the way how the filename hash is computed to make sure that the same function (same runtime, same source) can be deployed in different architectures? If there are any changes required, please make an issue about it and we take it in a separate PR.

2021-10-02 13:13 UTC, Infra-Red commented
Hi @antonbabenko, I've updated this PR in accordance with your comments, please review when you get a chance.

For the `package.{tf,py}` I see that it is possible to update the Lambda architecture without changing the filename:
1. Update a function to use different architecture:
     ```
    Terraform will perform the following actions:
    
      # module.lambda_function.aws_lambda_function.this[0] will be updated in-place
      ~ resource "aws_lambda_function" "this" {
          ~ architectures                  = [
              - "x86_64",
              + "arm64",
            ]
            id                             = "clear-earwig-lambda-async"
          ~ last_modified                  = "2021-10-02T13:04:47.276+0000" -> (known after apply)
            tags                           = {}
            # (18 unchanged attributes hidden)
    
            # (1 unchanged block hidden)
        }
    
    Plan: 0 to add, 1 to change, 0 to destroy.
    ```
1. Apply the changes:
    ```
    > terraform apply .plan
    module.lambda_function.aws_lambda_function.this[0]: Modifying... [id=clear-earwig-lambda-async]
    module.lambda_function.aws_lambda_function.this[0]: Modifications complete after 7s [id=clear-earwig-lambda-async]
    
    Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
    ```

2021-10-02 13:45 UTC, antonbabenko commented
Can you also update a complete example to show `compatible_architectures` in Lambda Layer? Then this PR will be good to merge.

2021-10-02 19:17 UTC, Infra-Red commented
Thanks @antonbabenko, `compete` example has been updated to include `compatible_architectures` in Lambda layers.

2021-10-02 19:19 UTC, antonbabenko approved these changes

2021-10-02 19:19 UTC, merged

2021-10-02 19:20 UTC, antonbabenko commented
Thank you, @Infra-Red !

[v2.20.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v2.20.0) has been just released.