chore: Added example for how to build container images with different architectures
terraform-aws-modules/terraform-aws-lambda pull request #344
Opened 2022-08-30 18:37 UTC by GonzalezAndrew

## Description

Added an example to showcase how one could build a container image on a build machine which might have a different architecture.

## Motivation and Context

I struggled to build a docker image using x86_64 architecture with this module when building container images from my local M1 Max mac machine until I found a workaround. #333 

The example I am adding is said work around and could be useful to those who also struggled like myself.

## Breaking Changes

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [X] I have executed `pre-commit run -a` on my pull request

I have tested this example by deploying the example lambda function in my personal AWS account. Additional screenshots demonstrating a deployment can be referenced here #333

2022-08-30 19:09 UTC, antonbabenko requested changes
Looks great! Could you please merge this new example into an existing container image example? The main difference between those is only `Dockerfile`.

Also, please update the description of the example in the parent README.md.

2022-08-30 23:08 UTC, GonzalezAndrew commented
Thanks for the review @antonbabenko 

I have done the changes you have requested and have tested the updated container-image example

![test](https://user-images.githubusercontent.com/42552579/187558927-429ae72e-8e14-498c-9849-27566dd75f0c.png)

Please let me know if there are any other additional changes that need to be made. Thanks.

2022-08-31 06:52 UTC, antonbabenko commented on examples/container-image/context/Dockerfile
> +FROM --platform=linux/x86_64 scratch
```suggestion
# `--platform` argument is used to be able to build docker images when using another platform (e.g. Apple M1)
FROM --platform=linux/x86_64 scratch
```

2022-08-31 06:53 UTC, antonbabenko approved these changes

2022-08-31 06:57 UTC, merged

2022-08-31 06:57 UTC, antonbabenko commented
Thank you @GonzalezAndrew !

2022-09-01 09:23 UTC, antonbabenko commented
This PR is included in version 4.0.1 :tada: