feat: add `logging_config`
terraform-aws-modules/terraform-aws-lambda pull request #531
Opened 2024-01-12 12:07 UTC by JoshuaLicense

## Description
Adds `logging_config` block for enabling [advanced logging](https://aws.amazon.com/blogs/compute/introducing-advanced-logging-controls-for-aws-lambda-functions/).

## Motivation and Context
Closes #530 

## Breaking Changes
No

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

2024-01-12 19:38 UTC, antonbabenko requested changes
Could you please update this module and handle the cases when the user specifies custom log group then default log group should not be created?

Maybe there are other cases that should be considered. I would appreciate if you can think about this and update this PR.

Also, maybe we need to update the log group in the outputs of the module if user specifies custom log group.

2024-01-12 19:38 UTC, antonbabenko commented on main.tf
> +      log_format            = var.logging_config_log_format
```suggestion
      log_format            = var.logging_log_format
```

Let's drop `config_` from variable names like we do in other places.

2024-01-12 22:09 UTC, JoshuaLicense commented
> Could you please update this module and handle the cases when the user specifies custom log group then default log group should not be created?
>
> Maybe there are other cases that should be considered. I would appreciate if you can think about this and update this PR.

My bad, thanks for the review. I've pushed some tweaks that handle the different log group scenarios better.
| `use_existing_cloudwatch_log_group` | `logging_log_group` | `aws_cloudwatch_log_group` created |
| --- | --- | --- |
| `true` | `null` | ❌ retrieved from data source: `"/aws/lambda/${var.lambda_at_edge ? "us-east-1." : ""}${var.function_name}"` |
| `true` | _populated_ | ❌ retrieved from data source: `var.logging_log_group` |
| `false` | `null` | ✅ 
| `false` | _populated_ | ❌ retrieved from data source: `var.logging_log_group`

> Also, maybe we need to update the log group in the outputs of the module if user specifies custom log group.

Existing data source is re-used so outputs should update appropriately.

2024-01-15 21:52 UTC, JoshuaLicense commented on main.tf
> +    for_each = var.logging_log_format != null ? [true] : []
`log_format` is required, it cannot be passed as `null`. 

https://github.com/hashicorp/terraform-provider-aws/blob/85b0843d0b3963876fcff0c5f55259239de8a558/internal/service/lambda/function.go#L250

Am I misunderstanding?

2024-01-19 12:30 UTC, antonbabenko approved these changes

2024-01-19 12:30 UTC, merged

2024-01-19 12:31 UTC, antonbabenko commented
This PR is included in version 7.0.0 :tada:

2024-01-30 00:42 UTC, AndrewCharlesHay commented
This causes breaks in Gov Cloud see #539