Use inline instead of managed policies
terraform-aws-modules/terraform-aws-lambda pull request #615
Opened 2024-08-29 11:51 UTC by RafaelWO

## Description
This MR replaces customer-managed policies with inline policies becuase the policies are only used for the Lambda function. See also [Managed policies and inline policies](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html#inline-policies).

## Motivation and Context
Fixes #607

## Breaking Changes
If users have attached the customer-managed policies to other resources, this change is breaking (in theory) since the new policies will be inline. But it is very unlikely that users did this.

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

2024-08-30 08:50 UTC, RafaelWO commented
> From the first look at this PR, it looks pretty good, but why are only some policy attachments changed? Should we update `vpc`, `tracing`, etc also?

Happy to change those as well but I was not sure because it looks like it they are copied from AWS-managed policies:

> Copying AWS managed policy to be able to attach the same policy with multiple roles without overwrites by another function

Apparently, there was an issue with only creating an `aws_iam_role_policy_attachment` with the AWS-managed policy ARN (see https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/26). Or is this obsolete?

2024-09-02 15:32 UTC, RafaelWO commented
> Should we update vpc, tracing, etc also?


@antonbabenko, or did you mean using the policy from the "copy" data block in a `aws_iam_role_policy`? I.e. changing

```tf
# Copying AWS managed policy to be able to attach the same policy with multiple roles without overwrites by another function
data "aws_iam_policy" "vpc" {
  count = local.create_role && var.attach_network_policy ? 1 : 0
  arn = "arn:${data.aws_partition.current.partition}:iam::aws:policy/service-role/AWSLambdaENIManagementAccess"
}

resource "aws_iam_policy" "vpc" {
  count = local.create_role && var.attach_network_policy ? 1 : 0
  name   = "${local.policy_name}-vpc"
  path   = var.policy_path
  policy = data.aws_iam_policy.vpc[0].policy
  tags   = var.tags
}

resource "aws_iam_role_policy_attachment" "vpc" {
  count = local.create_role && var.attach_network_policy ? 1 : 0
  role       = aws_iam_role.lambda[0].name
  policy_arn = aws_iam_policy.vpc[0].arn
}
```

to

```tf
# Copying AWS managed policy to be able to attach the same policy with multiple roles without overwrites by another function
data "aws_iam_policy" "vpc" {
  count = local.create_role && var.attach_network_policy ? 1 : 0
  arn = "arn:${data.aws_partition.current.partition}:iam::aws:policy/service-role/AWSLambdaENIManagementAccess"
}

resource "aws_iam_role_policy" "vpc" {
  count = local.create_role && var.attach_network_policy ? 1 : 0
  name   = "${local.policy_name}-vpc"
  role   = aws_iam_role.lambda[0].name
  policy = data.aws_iam_policy.vpc[0].policy
}
```

2024-10-04 11:43 UTC, RafaelWO commented
> Should we update vpc, tracing, etc also?

@antonbabenko, I updated `vpc` and `tracing` as well (as described in my comment above. I don't think there is anything left, or is there?

2024-11-07 07:18 UTC, RafaelWO commented
@antonbabenko Looking forward to your review :slightly_smiling_face:

2024-12-10 14:01 UTC, RafaelWO commented
@antonbabenko ping :slightly_smiling_face:

2024-12-24 18:20 UTC, hossamdash commented
would be great if this gets merged!

2025-01-07 23:17 UTC, antonbabenko requested changes
Minor correction is missing. I have already reviewed other dependencies and potential issues. Looks great! Sorry that it took so long for me to review it!

2025-01-07 23:17 UTC, antonbabenko commented on main.tf
> -    aws_iam_role_policy_attachment.tracing,
I think, yes. Do you agree, @RafaelWO ? If so, please fix it, and I will merge it very quickly.

2025-01-08 06:38 UTC, RafaelWO commented on main.tf
> -    aws_iam_role_policy_attachment.tracing,
Sounds good! I fixed it :slightly_smiling_face:

2025-01-08 06:46 UTC, RafaelWO commented
I guess I somehow messed up the PR by rebasing after the master was merged into my branch :grimacing: 

Should I open a new clean PR with my changes?

2025-01-08 20:26 UTC, antonbabenko approved these changes

2025-01-08 20:43 UTC, merged

2025-01-08 20:44 UTC, antonbabenko commented
This PR is included in version 7.20.0 :tada:

2025-01-08 20:48 UTC, antonbabenko commented
@RafaelWO Thank you a lot for this contribution!

2025-01-08 21:01 UTC, RafaelWO commented
It was a pleasure 😊