feat: Support Event Source Mapping `metrics_config`, `provisioned_poller_config`, and Lambda Recursion Loop
terraform-aws-modules/terraform-aws-lambda pull request #649
Opened 2024-12-08 15:10 UTC by magreenbaum

## Description
Supports arguments `aws_lambda_event_source_mapping.metrics_config`, `aws_lambda_event_source_mapping.provisioned_poller_config` and resource for `aws_lambda_function_recursion_config`. 

## Motivation and Context
- https://github.com/hashicorp/terraform-provider-aws/pull/40322 
- https://github.com/hashicorp/terraform-provider-aws/issues/40303
- Closes: https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/643

## Breaking Changes
No.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

2024-12-08 20:09 UTC, antonbabenko requested changes

2024-12-08 20:09 UTC, antonbabenko commented on main.tf
> +  function_name  = var.function_name
```suggestion
  function_name  = aws_lambda_function.this[0].function_name
```

Then we don't need `depends_on`.

2024-12-08 20:09 UTC, antonbabenko commented on main.tf
> +  count = local.create && var.recursive_loop == "Allow" ? 1 : 0
```suggestion
  count = local.create && var.create_function && !var.create_layer && var.recursive_loop == "Allow" ? 1 : 0
```

2024-12-08 21:47 UTC, antonbabenko approved these changes

2024-12-08 21:48 UTC, merged

2024-12-08 21:48 UTC, antonbabenko commented
This PR is included in version 7.17.0 :tada:

2024-12-09 09:25 UTC, ikuwow commented on examples/alias/versions.tf
> +      version = ">= 5.79"
This is a breaking change.
This changes should be noted in CHANGELOG.md.
https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/CHANGELOG.md#7170-2024-12-08

2024-12-09 09:26 UTC, ikuwow commented on versions.tf
> +      version = ">= 5.79"
This is a breaking change.
This changes should be noted in CHANGELOG.md.
https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/CHANGELOG.md#7170-2024-12-08